### PR TITLE
Some more python 3 fixes

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by ale-rt** [comment]
@dataflake my fault, I did #70 and then cherry picked it on this branch :/

**Comment by dataflake** [comment]
@ale-rt is this PR still needed then? just wondering.

**Comment by ale-rt** [comment]
I have to cross check with @pbauer, if we could merge #70 first then we can come out with a cleaner PR

**Comment by ale-rt** [comment]
@dataflake forgot to mention that if you are willing to merge this one #70 can be just closed

**Comment by dataflake** [comment]
@ale-rt With these string handling fixes I would rather go smaller steps and merge #70

**Comment by dataflake** [comment]
I've merged #69 now

**Comment by icemac** [comment]
> I've merged #69 now

Hm, but the PR is still open?

**Comment by dataflake** [comment]
Please stop adding stuff here, the branch has been merged!

**Pull request closed without merging**
