### PR TITLE
WIP replace zope.formlib by z3c.form

### PR DESCRIPTION
**Pull request by gforcada**
Fixes
https://github.com/zopefoundation/Products.GenericSetup/issues/31

This is WIP so far.

### CODE REVIEW

**Comment by tseaver** [comment]
Needs to update the `install_requires` entry in `setup.py` too (might explain the test failures).

**Comment by gforcada** [comment]
@tseaver it's already in, it probably needs to load z3c.form's meta.zcml...

**Comment by tseaver** [comment]
@gforcada Thanks for the patch!  Any reason it is sill "WIP"?

**Comment by gforcada** [comment]
I still haven't check how it looks like, or is the coverage big enough to be confident that everything is in place?

**Comment by gforcada** [comment]
Seems to be totally broken :-( If you open the ZMI and go to Components tabs it gives the following traceback:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module z3c.form.form, line 239, in __call__
  Module z3c.form.form, line 163, in render
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 261, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module 4139b51603283774fe9ae5c3f74f01aa.py, line 170, in render
  Module five.pt.expressions, line 154, in __call__
  Module five.pt.expressions, line 126, in traverse
  Module zope.traversing.adapters, line 136, in traversePathElement
   - __traceback_info__: (None, 'macros')
  Module zope.traversing.adapters, line 50, in traverse
   - __traceback_info__: (None, 'macros', ('form',))
LocationError: (None, 'macros')

 - Expression: "view/base_template/macros/form"
 - Filename:   ... GenericSetup/Products/GenericSetup/browser/components.pt
 - Location:   (line 19: col 30)
 - Source:     ... metal:use-macro="view/base_template/macros/form" />
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f0cbb341b90>
               views: <ViewMapper - at 0x7f0cb8f4b250>
               modules: <instance - at 0x7f0cc6c1bd88>
               args: <tuple - at 0x7f0cd3e3c050>
               here: <ImplicitAcquisitionWrapper Plone at 0x7f0cbb436c80>
               user: <ImplicitAcquisitionWrapper - at 0x7f0cbb41ba00>
               nothing: <NoneType - at 0x7f0cd3c41dc0>
               container: <ImplicitAcquisitionWrapper Plone at 0x7f0cbb436c80>
               request: <instance - at 0x7f0cb9df3638>
               wrapped_repeat: <SafeMapping - at 0x7f0cb8e2ad08>
               traverse_subpath: <list - at 0x7f0cb8dd1f38>
               default: <object - at 0x7f0cd3e12590>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper Plone at 0x7f0cbb436c80>
               view: <ComponentsSetupTab manage_components at 0x7f0cb7b21710>
               translate: <function translate at 0x7f0cb7af9a28>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f0cbb648280>
               options: {...} (0)
               target_language: <NoneType - at 0x7f0cd3c41dc0>
```

**Comment by gforcada** [comment]
@tseaver I fixed the template by using plone.z3cform to render it, would that be ok to add it as a dependency? I have no idea how to render the form directly with z3c.form, any hints? Or plone.z3cform dependency is ok?

**Comment by mauritsvanrees** [comment]
I briefly talked about this with Gil at the Plone conference in Boston. We were thinking: wouldn't it be better to do this manually, without any form library at all?  The only field that we need to handle is a single textarea. That can be done in a normal browser view.

**Comment by davisagli** [comment]
+1 to not using a form library here

**Comment by gforcada** [comment]
Closing this one then, #34 is far a better idea

**Pull request closed without merging**
