### PR TITLE
Updates to davisagli-py-3 branch

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
@davisagli if you are committing to this branch it might have sense to merge this branch into your (the original one I did not want to mess up).

**Comment by ale-rt** [comment]
Thanks! Probably some of the changes are still needed to have Products.CMFCore tests green, but we can't sort this out the next week.
I will not be at the sprint but I will try to be available remotely :)

**Comment by dataflake** [comment]
Tests are actually all green in CMFCore: https://github.com/zopefoundation/Products.CMFCore/pull/42. That is ready to merge as well.

**Comment by ale-rt** [comment]
The tests are green because they are using this branch: https://github.com/zopefoundation/Products.CMFCore/pull/42/files#diff-a55fc4e553af13234f26342646b88e19R19 :)

**Comment by dataflake** [comment]
Closing the pull request, I pulled all I needed from that branch.

**Comment by davisagli** [comment]
Thanks for sorting that out, @dataflake

**Pull request closed without merging**
