### PR TITLE
Add Python 3.7 support.

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by jamadden** [comment]
Previously `PythonIdentifier` only did validation if you specifically called `validate()`. If you just used `fromUnicode()`, *anything* that could be used by `TextLine` was allowed. So swapping the field to `TextLine` is the most direct migration path.

That said, I don't know anything about the semantics of this project and whether those things really *should* be python identifiers or not. Which is probably why you're asking the opinion of @tseaver 😄

**Comment by tseaver** [comment]
I believe that the original intent was to use only identifiers for the `name` attributes of `<gs:registerProfile>`, `<gs:exportStep>`, `<gs:importStep>` (and for the `<depends>` subkey of `<gs:importStep>`), but that ship has sailed.  Even if we fix the tests here, there are probably dozens of cases of dotted names out in the wild.

**Comment by davisagli** [comment]
Plone definitely uses steps with dots and dashes in the names.

**Comment by icemac** [comment]
@davisagli I changed all usages of `PythonIdentifier` in `zcml.py` to `TextLine` as suggested by @jamadden. This makes at least the tests green. In Products.CMFPlone#2591 you suggest to use `ASCIILine`. Is this actually a requirement or is `TextLine` good enough?

**Comment by davisagli** [comment]
@icemac I'm not sure if it actually matters, but I thought ASCIILine would be safer in order to be a native string in both Pythons, like Python identifiers are.

**Comment by icemac** [comment]
@davisagli Good point, I'll change it to `ASCIILine`.

**Comment by icemac** [comment]
@davisagli Before `zope.configuration 4.2` the class `zope.configuration.fields.PythonIdentifier` was a subclass of `zope.schema.TextLine`. So the values where always `text`. After having found out that, I am preferring `TextLine` over `ASCIILine` as the latter one would additionally force to change the `default` values of the fields from `unicode` to `str`.

**Pull request merged**
